### PR TITLE
Cookies-banner updated

### PR DESCRIPTION
**Pull request by lguilhermef**
I just added these portions:

after <html>

  <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/cookieconsent@3/build/cookieconsent.min.css" />

before </body>

    <script>
        window.cookieconsent.initialise({
          "palette": {
            "popup": {
              "background": "#000000"
            },
            "button": {
              "background": "#ef404a"
            }
          },
          "theme": "edgeless",
          "position": "top",
          "static": true,
          "type": "opt-in"
        });
    </script>

### CODE REVIEW

**Comment by spaudanjo** [comment]
Visually it looks great and works! :) 
But I checked (after having cleared all my local cookies for the landing page) and Google Analytics cookies were set even before I accepted the consent dialog. There doesn't seem to be any js handler logic which deactivates/activates GA based on the result of the dialog. 
I think GA is not considered to be a technical essential cookie case and without explicit user consent, to my best knowledge it violates GDPR. 

image

I found this medium article, but didn't go through it yet - it might help to make the needed connection between consent dialog and GA/Tagmanager: 
https://medium.com/lets-get-digital/free-gdpr-cookie-consent-notification-with-google-tag-manager-327e53e6fb82

If we cannot fix it in a reasonable amount of time (whatever this exactly is :D), maybe it's better to remove GA/Tagmanager for now?

**Review by spaudanjo — CHANGES_REQUESTED** [review]
Visually it looks great and works! :) 
But I checked (after having cleared all my local cookies for the landing page) and Google Analytics cookies were set even before I accepted the consent dialog. There doesn't seem to be any js handler logic which deactivates/activates GA based on the result of the dialog. 
I think GA is not considered to be a technical essential cookie case and without explicit user consent, to my best knowledge it violates GDPR. 

image

I found this medium article, but didn't go through it yet - it might help to make the needed connection between consent dialog and GA/Tagmanager: 
https://medium.com/lets-get-digital/free-gdpr-cookie-consent-notification-with-google-tag-manager-327e53e6fb82

If we cannot fix it in a reasonable amount of time (whatever this exactly is :D), maybe it's better to remove GA/Tagmanager for now?

**Comment by spaudanjo** [comment]
As discussed in todays meeting: since we removed Google Tag Manager now and don't have any cookies anymore, agreement was to: 
* close this PR 
* and create a follow up task for removing the whole cookie banner

**Comment by aerinsol** [comment]
@spaudanjo I don't think we need to remove the code per se, we may need it in the future. It's fairly lightweight and simple so we can save it for another day.

**Pull request closed without merging**
